In [ ]:
# Data manipulation
import pandas as pd
import numpy as np
import helpers as hp

# Viz
import matplotlib.pyplot as plt
import seaborn as sns

# Dev
import importlib
importlib.reload(hp)

# Display
sns.set_style("whitegrid")
pd.options.display.max_columns = 200
pd.options.display.max_rows = 200

## Clean all data

In [ ]:
hp.clean_all()

## Load cleaned data

In [ ]:
orgs = hp.read_feather("data/cleaned/organizations.feather")
cand = hp.read_feather("data/cleaned/candidates.feather")
jobs = hp.read_feather("data/cleaned/jobs.feather")
apps = hp.read_feather("data/cleaned/applications.feather")
hist = hp.read_feather("data/cleaned/histories.feather")

## Preview data

Organizations

In [ ]:
orgs.head(1)

,org_id,org_name,org_industry,org_type,org_country,org_city
0,001b00000047HAQAA2,Candidate Pool,Technology,NaN,ITALY,MILAN

Candidates

In [ ]:
cands.head(1)

,cand_id,cand_edu,cand_skills,cand_it_skills,cand_general_skills,cand_other_skills,cand_current_title,cand_current_employer,cand_prev_titles,cand_prev_employers,cand_summary,cand_shortlist,cand_country,cand_city,cand_created_at
0,0036700003YdjftAAB,Bocconi University Milan IT Master of Sc...,BUSINESS INTELLIGENCE;BUSINESS INTELLIGENCE;MI...,ETL;PLATFORM AS A SERVICE;AMAZON WEB SERVICES;...,NaN,ENGLISH;ITALIAN;FRENCH;GERMAN;JAPANESE;RUSSIAN...,REMOTE WORK,BUSINESS INTELLIGENCE CONSULTING,DATA PRODUCT LEAD;HEAD OF BUSINESS INTELLIGENC...,SHOPFULLY INTERNATIONAL GROUP;DAWANDA GMBH.;BU...,I am a link between the technical work of Busi...,ARTIFICIAL INTELLIGENCE,IT,MILAN,2019-01-09 15:16:27

Jobs

In [ ]:
jobs.head(1)

,job_id,job_title,job_description,job_category,job_term,job_contract,job_n_positions,job_reason,job_experience,job_skills,job_team_lead_size,job_project_management,job_pct_travel,job_lang_1,job_lang_2,job_lang_1_level,job_lang_2_level,job_salary,job_bonus,job_benefit,job_locations,job_osn_practice,job_fee,job_created_at,job_total_salary
0,a0Fb0000003SB4AEAW,ANALYST PROGRAMMER BIG DATA,"Una societa? di System Interation , nostra cl...",CONSULTING,Permanent,Permanent,3.0,Increase in HC,04-06 years,BIG DATA;HADOOP;HIVE;HBASE;DIGITAL INTELLIGENC...,3-5,Yes,100%,English,Italian,Basic User,Basic User,55000.0,0.0,MEAL COUPONS;MOBILE;LAPTOP,MILAN,DATA ENGINEERING,20.0,2014-04-19 08:22:48,55000.0

Job applications

In [ ]:
apps.head(1)

,app_id,org_id,cand_id,job_id,app_job_title,app_cv,app_current_role,app_contract,app_city,app_reject_qualifier,app_stage,app_created_at,app_cv_received_at
0,a0Db000000VHhmrEAD,001b0000009VWc1AAG,003b0000013RrinAAC,a0Fb000000EGSTkEAP,DATA SCIENTIST,2 Federica Membretti +39 340 81 95 9...,NaN,Perm,VIMODRONE,DECLINED POSITION,Sent to client - Withdraw,2015-11-17 14:00:20,2016-02-18

Employment histories

In [ ]:
hist.head(1)

,hist_id,cand_id,hist_description,hist_org,hist_start_at,hist_end_at,hist_created_at,hist_years
0,a0Ab0000001nDaTEAU,003b0000006JthTAAS,Create relationships with Enterprise & Emergin...,SAP,2009-08-01,NaT,2013-06-03 22:45:30,3.8